### ISSUE TITLE
New join broadcasts

### ISSUE THREAD

**Issue by WitherSkeletons** [PenguinHi5/NewJoinCounter#1]
Hello,
The plugin is not making broadcasts on the event of a new player joining, however it is logging the uuid to the database

**Comment by PenguinHi5** [comment]
Does the player joining the server see the broadcast or does nobody see it?

**Comment by WitherSkeletons** [comment]
Nope I tried it with multiple accounts after resetting the database

**Comment by PenguinHi5** [comment]
Sorry for the late reply, I got home from my class not long ago and got distracted by a job interview offer.
What version of bukkit/spigot are you using and does any errors appeal in the console? Also, can you send me a copy of your config? (minus the database credentials)

**Comment by WitherSkeletons** [comment]
I'm using PaperSpigot 1.8.8
Config:
# NewJoinCounter Configuration -- Configuration Help at https://github.com/PenguinHi5/NewJoinCounter/wiki/Config.yml

mysql:
  hostname: -
  port: -
  database: -
  username: -
  password: -
  table: NewJoinCounter
join-message: '&3Welcome &b%player(&7#%number&b) &3to the server!'
broadcast-global-message: false

**Comment by WitherSkeletons** [comment]
That didn't paste in properly above http://hastebin.com/ofeheduvop.sm

**Comment by PenguinHi5** [comment]
Okay, I believe I fixed it.
https://www.dropbox.com/s/bnc9fwyamyfao10/NewJoinCounter.jar?dl=1
If the plugin doesn't do it on it's own feel free to remove the 'broadcast-global-message' line, as it is no longer needed.
